DELETE FROM tapplications;
DELETE FROM tseats;
DELETE FROM ttrips;
DELETE FROM tusers;
INSERT INTO "PUBLIC"."TUSERS" ( "EMAIL", "LOGIN", "NAME", "PASSWORD", "STATUS", "SURNAME" ) VALUES ( 'test3', 'test3', 'test3', 'test',1 , 'test3');
INSERT INTO "PUBLIC"."TUSERS" (  "EMAIL", "LOGIN", "NAME", "PASSWORD", "STATUS", "SURNAME" ) VALUES (  'test4', 'test4', 'test4', 'test',1 , 'test4');
INSERT INTO "PUBLIC"."TUSERS" (  "EMAIL", "LOGIN", "NAME", "PASSWORD", "STATUS", "SURNAME" ) VALUES (  'test5', 'test5', 'test5', 'test',1 , 'test5');
INSERT INTO "PUBLIC"."TUSERS" (  "EMAIL", "LOGIN", "NAME", "PASSWORD", "STATUS", "SURNAME" ) VALUES (  'test6', 'test6', 'test6', 'test',1 , 'test6');
INSERT INTO "PUBLIC"."TUSERS" (  "EMAIL", "LOGIN", "NAME", "PASSWORD", "STATUS", "SURNAME" ) VALUES (  'test7', 'test7', 'test7', 'test',1 , 'test7');
INSERT INTO "PUBLIC"."TUSERS" (  "EMAIL", "LOGIN", "NAME", "PASSWORD", "STATUS", "SURNAME" ) VALUES (  'test8', 'test8', 'test8', 'test',1 , 'test8');